name: Jenkins Setup

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Run Jenkins Setup
        uses: jenkinsci/jfr-setup-action@master
        with:
          jenkins-version: 2.503
          jenkins-core-url: https://updates.jenkins.io/download/war/2.503/jenkins.war
          jenkins-pm-version: 2.5.0
          jfr-version: 1.0-beta-30
          jenkins-pm-url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.5.0/jenkins-plugin-manager-2.5.0.jar
          jenkins-jfr-url: https://github.com/jenkinsci/jenkinsfile-runner/releases/download/1.0-beta-30/jenkinsfile-runner-1.0-beta-30.zip
